version: '3.8'
services:
  app:
    image: myproject1-app:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/myprojectdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 2702
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 2702
      MYSQL_DATABASE: myprojectdb
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
