version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: myproject-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 2702
      MYSQL_DATABASE: myprojectdb
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 10  # Tăng số lần thử kiểm tra trạng thái của MySQL
      timeout: 20s  # Thời gian chờ mỗi lần kiểm tra

  app:
    image: myproject1-app:latest
    container_name: myproject1-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/myprojectdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 2702
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy  # Chỉ khởi động khi MySQL đã sẵn sàng
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
