name: Docker Login
description: "Log in to Docker Hub"
inputs:
  docker_username:
    description: "Docker Hub username"
    required: true
  docker_password:
    description: "Docker Hub password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Log in to Docker Hub
      run: |
        echo "${{ inputs.docker_password }}" | docker login -u "${{ inputs.docker_username }}" --password-stdin
      shell: bash
