name: Docker Login
description: "Log in to Docker Hub"
runs:
  using: "composite"
  steps:
    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
