name: Set up JDK
description: "Set up JDK 17"

runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      java-version: '17'
      run: |
        java -version
        echo "Current working directory: $(pwd)"
        echo "Listing all files and directories after setting up JDK:"
        ls -al
        echo "JDK 17 setup completed successfully."
      shell: bash  # Thêm thuộc tính shell ở đây
