name: Run Health Check
description: "Run health check on the Spring Boot application"
runs:
  using: "composite"
  steps:
    - name: Run Health Check
      run: |
        sleep 60
        curl -v http://localhost:8080/actuator/health || echo "Health check failed"
      shell: bash