name: Run MySQL Container
description: "Run MySQL container"
runs:
  using: "composite"
  steps:
    - name: Run MySQL Container
      run: |
        if [ ! -d /tmp/shared_data ]; then
          sudo mkdir -p /tmp/shared_data
        fi
        sudo chown -R 999:999 /tmp/shared_data
        docker run -d --name myproject-mysql --network myproject-network \
          -e MYSQL_ROOT_PASSWORD=2702 \
          -e MYSQL_DATABASE=myprojectdb \
          -v /tmp/shared_data:/shared_data \
          -p 3306:3306 mysql:8.0
