# Tên của workflow này để dễ nhận diện
name: Build, Test, and Deploy Spring Boot Application with Docker Compose

# 1. Event - Kích hoạt workflow khi có sự kiện push hoặc pull request lên nhánh master
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Định nghĩa các công việc (jobs) trong workflow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 4. Step - Check out mã nguồn từ repository
      - name: Check out code
        uses: actions/checkout@v4

      # 5. Step - Thiết lập JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 6. Step - Build ứng dụng với Maven
      - name: Build with Maven
        run: |
          echo "Building the project using Maven..."
          mvn clean install
          echo "Maven build completed."

      # 7. Step - Đăng nhập Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 8. Step - Build Docker image
      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t myproject1-app:latest .
          echo "Docker image build completed."

      # 9. Step - Liệt kê Docker image
      - name: List Docker Images
        run: |
          echo "Listing Docker images to verify build..."
          docker images  # Liệt kê tất cả các Docker images để kiểm tra xem `myproject1-app:latest` có tồn tại không

      # 10. Step - Tag và push Docker image lên Docker Hub
      - name: Tag and Push Docker Image
        run: |
          echo "Tagging Docker image: myproject1-app:latest..."
          docker tag myproject1-app:latest ${{ secrets.DOCKER_USERNAME }}/myproject1:latest
          echo "Pushing Docker image to Docker Hub..."
          docker push ${{ secrets.DOCKER_USERNAME }}/myproject1:latest
          echo "Docker image pushed successfully."

      # 11. Step - Cài đặt Docker Compose
      - name: Install Docker Compose
        run: |
          echo "Installing Docker Compose..."
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version  # Xác nhận Docker Compose đã được cài đặt
          echo "Docker Compose installed."

      # 12. Step - Thiết lập Docker Compose
      - name: Set up Docker Compose
        run: |
          echo "Starting Docker Compose with docker-compose.yml..."
          docker-compose -f docker-compose.yml up -d --build  # Khởi động cả MySQL và Spring Boot
          echo "Docker Compose started."

      # 13. Step - Kiểm tra trạng thái của tất cả container
      - name: Check Running Docker Containers
        run: |
          echo "Listing all running Docker containers..."
          docker ps -a  # In ra tất cả các container (đang chạy và đã dừng)
          echo "Container status checked."

      # 14. Step - Kiểm tra log của tất cả các container (bao gồm cả MySQL và Spring Boot)
      - name: Check All Container Logs
        run: |
          echo "Checking logs of all containers..."
          docker logs myproject1-app || echo "Failed to retrieve Spring Boot logs"
          docker logs myproject1-db || echo "Failed to retrieve MySQL logs"  # Giả định container DB là myproject1-db
          echo "All container logs checked."

      # 15. Step - Chạy kiểm tra sức khỏe (health check) của ứng dụng với debug
      - name: Run Health Check
        run: |
          echo "Waiting for the application to be ready..."
          sleep 60  # Đợi thêm thời gian để ứng dụng Spring Boot khởi động
          echo "Running health check on the application..."
          curl -v http://localhost:8080/actuator/health || echo "Health check failed"
          echo "Health check completed."
