# Tên của workflow này để dễ nhận diện
name: Build, Test, and Deploy Spring Boot Application with Docker

# 1. Event - Kích hoạt workflow khi có sự kiện push hoặc pull request lên nhánh master
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Định nghĩa các công việc (jobs) trong workflow
jobs:
  # 3. Job - Một job để build, test, và deploy ứng dụng
  build:
    # 5. Runner - Chạy job trên một runner Ubuntu mới nhất
    runs-on: ubuntu-latest

    steps:
      # 4. Step - Check out mã nguồn từ repository
      - name: Check out code
        uses: actions/checkout@v4

      # 4. Step - Thiết lập JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 4. Step - Build ứng dụng với Maven
      - name: Build with Maven
        run: mvn clean install

      # 5. Step - Build Docker image
      - name: Build Docker Image
        run: docker build -t myproject1:latest .

      # 6. Step - Log in to Docker Hub (replace DOCKER_USERNAME and DOCKER_PASSWORD with your GitHub Secrets)
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # **Step to log Docker images**
      - name: List Docker Images
        run: docker images  # Liệt kê tất cả các Docker images để kiểm tra xem `myproject1:latest` có tồn tại không

      # **Step to log running containers (if any)**
      - name: List Running Docker Containers
        run: docker ps -a  # Liệt kê tất cả các Docker containers (cả đang chạy và dừng)

      # 7. Step - Tag và push Docker image lên Docker Hub
      - name: Tag and Push Docker Image
        run: |
          docker tag myproject1:latest ${{ secrets.DOCKER_USERNAME }}/myproject1:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/myproject1:latest

      # 8. Step - Chạy container từ Docker image (cho mục đích kiểm thử)
      - name: Run Docker Container for Testing
        run: |
          echo "Starting container from Docker image: ${{ secrets.DOCKER_USERNAME }}/myproject1:latest"
          docker run -d -p 8080:8080 --name myproject1-container ${{ secrets.DOCKER_USERNAME }}/myproject1:latest
          echo "Container started, waiting for the application to be ready..."
          sleep 30  # Thêm thời gian chờ để đảm bảo ứng dụng có đủ thời gian để khởi động
          echo "Checking running containers:"
          docker ps -a  # In ra danh sách container đang chạy
          echo "Checking logs of the container:"
          docker logs myproject1-container  # Kiểm tra log của container để xem ứng dụng có khởi động thành công không
          echo "Running health check on the application:"
          curl -f http://localhost:8080/actuator/health || echo "Health check failed"