# Tên của workflow này để dễ nhận diện
name: Build, Test, and Deploy Spring Boot Application with Docker

# 1. Event - Kích hoạt workflow khi có sự kiện push hoặc pull request lên nhánh master
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Định nghĩa các công việc (jobs) trong workflow
jobs:
  # 3. Job - Một job để build, test, và deploy ứng dụng
  build:
    # 5. Runner - Chạy job trên một runner Ubuntu mới nhất
    runs-on: ubuntu-latest

    steps:
      # 4. Step - Check out mã nguồn từ repository
      - name: Check out code
        uses: actions/checkout@v4

      # 4. Step - Thiết lập JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 4. Step - Build ứng dụng với Maven
      - name: Build with Maven
        run: mvn clean install

      # 5. Step - Build Docker image
      - name: Build Docker Image
        run: docker build -t myproject1:latest .

      # 6. Step - Log in to Docker Hub (replace DOCKER_USERNAME and DOCKER_PASSWORD with your GitHub Secrets)
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 7. Step - Tag và push Docker image lên Docker Hub
      - name: Tag and Push Docker Image
        run: |
          docker tag myproject1:latest ${{ secrets.DOCKER_USERNAME }}/myproject1:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/myproject1:latest

      # 8. Step - Chạy container từ Docker image (cho mục đích kiểm thử)
      - name: Run Docker Container for Testing
        run: |
          docker run -d -p 8080:8080 --name myproject1-container ${{ secrets.DOCKER_USERNAME }}/myproject1:latest
          sleep 10  # Đợi container khởi động
          curl -f http://localhost:8080/actuator/health  # Kiểm tra ứng dụng có hoạt động không
