# Tên của workflow này để dễ nhận diện
name: Build, Test, and Deploy Spring Boot Application with Docker

# Kích hoạt workflow khi có sự kiện push hoặc pull request lên nhánh master
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out mã nguồn từ repository
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Thiết lập JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Build ứng dụng với Maven
      - name: Build with Maven
        run: |
          echo "Building the project using Maven..."
          mvn clean install
          echo "Maven build completed."

      # 4. Đăng nhập Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 5. Build Docker image
      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t myproject1-app:latest .
          echo "Docker image build completed."

      # 6. Liệt kê Docker image
      - name: List Docker Images
        run: |
          echo "Listing Docker images to verify build..."
          docker images

      # 7. Tạo Docker network
      - name: Create Docker Network
        run: |
          echo "Creating Docker network..."
          docker network create myproject-network
          echo "Docker network created."

      # 8. Chạy MySQL container trong Docker network
      - name: Run MySQL Container
        run: |
          echo "Running MySQL container..."
          docker run -d --name myproject-mysql --network myproject-network -e MYSQL_ROOT_PASSWORD=2702 -e MYSQL_DATABASE=myprojectdb -p 3306:3306 mysql:8.0
          echo "MySQL container is running."

      # 9. Đợi MySQL khởi động và sẵn sàng
      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          sleep 30  # Thời gian chờ để MySQL khởi động
          echo "MySQL should be ready now."

      # 10. Chạy ứng dụng Spring Boot với Docker run, trong cùng network
      - name: Run Spring Boot Container with Docker Run
        run: |
          echo "Running Spring Boot application with Docker Run..."
          docker run -d --name myproject1-container --network myproject-network -p 8080:8080 -e SPRING_DATASOURCE_URL=jdbc:mysql://myproject-mysql:3306/myprojectdb -e SPRING_DATASOURCE_USERNAME=root -e SPRING_DATASOURCE_PASSWORD=2702 myproject1-app:latest
          echo "Spring Boot application is running."

      # 11. Kiểm tra log chi tiết của ứng dụng Spring Boot
      - name: Check Detailed Spring Boot Logs
        run: |
          echo "Checking detailed logs of the Spring Boot application..."
          docker logs -f myproject1-container || echo "Failed to retrieve Spring Boot logs"
          echo "Spring Boot logs checked."

      # 12. Chạy kiểm tra sức khỏe (health check) của ứng dụng với curl
      - name: Run Health Check
        run: |
          echo "Waiting for the application to be ready..."
          sleep 60  # Thời gian chờ để ứng dụng khởi động
          echo "Running health check on the application..."
          curl -v http://localhost:8080/actuator/health || echo "Health check failed"
          echo "Health check completed."

      # 13. Kiểm tra trạng thái container
      - name: Check Running Docker Containers
        run: |
          echo "Listing all running Docker containers..."
          docker ps -a
          echo "Container status checked."
