# Tên của workflow này để dễ nhận diện
name: Build, Test, and Deploy Spring Boot Application with Docker Compose

# 1. Event - Kích hoạt workflow khi có sự kiện push hoặc pull request lên nhánh master
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Định nghĩa các công việc (jobs) trong workflow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 4. Step - Check out mã nguồn từ repository
      - name: Check out code
        uses: actions/checkout@v4

      # 5. Step - Thiết lập JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 6. Step - Build ứng dụng với Maven, thêm debug log để quan sát
      - name: Build with Maven
        run: |
          echo "Building the project using Maven..."
          mvn clean install
          echo "Maven build completed."

      # 7. Step - Thiết lập Docker Compose, thêm debug log
      - name: Set up Docker Compose
        run: |
          echo "Starting Docker Compose with docker-compose.yml..."
          docker-compose -f docker-compose.yml up -d  # Khởi động cả MySQL và Spring Boot
          echo "Docker Compose started."

      # 8. Step - Kiểm tra trạng thái của các container, thêm debug log
      - name: Check Running Docker Containers
        run: |
          echo "Listing all running Docker containers..."
          docker ps -a  # In ra danh sách các container đang chạy
          echo "Container status checked."

      # 9. Step - Kiểm tra log của ứng dụng, thêm debug log
      - name: Check Application Logs
        run: |
          echo "Checking logs of the Spring Boot application..."
          docker logs myproject1-app  # Kiểm tra log của ứng dụng Spring Boot để đảm bảo rằng nó đã khởi động thành công
          echo "Application logs checked."

      # 10. Step - Chạy kiểm tra sức khỏe (health check) của ứng dụng, thêm debug log
      - name: Run Health Check
        run: |
          echo "Waiting for the application to be ready..."
          sleep 30  # Đợi một khoảng thời gian để ứng dụng Spring Boot khởi động
          echo "Running health check on the application..."
          curl -f http://localhost:8080/actuator/health || echo "Health check failed"
          echo "Health check completed."

      # 11. Step - Đăng nhập Docker Hub và push image, thêm debug log
      - name: Log in to Docker Hub
        run: |
          echo "Logging into Docker Hub..."
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          echo "Login to Docker Hub completed."

      # 12. Step - Tag và push Docker image lên Docker Hub, thêm debug log
      - name: Tag and Push Docker Image
        run: |
          echo "Tagging Docker image: myproject1-app:latest..."
          docker tag myproject1-app:latest ${{ secrets.DOCKER_USERNAME }}/myproject1:latest
          echo "Pushing Docker image to Docker Hub..."
          docker push ${{ secrets.DOCKER_USERNAME }}/myproject1:latest
          echo "Docker image pushed successfully."
