name: Build, Test, and Deploy Spring Boot Application with Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Log in to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 600627348552.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t myproject1-app:latest .

      - name: Tag Docker image
        run: docker tag myproject1-app:latest 600627348552.dkr.ecr.us-east-1.amazonaws.com/myproject1-app-repo:latest

      - name: Push Docker image to AWS ECR
        run: docker push 600627348552.dkr.ecr.us-east-1.amazonaws.com/myproject1-app-repo:latest

      - name: Update ECS service with new image
        run: |
          aws ecs update-service \
            --cluster myproject1-app-cluster \
            --service myproject1-app-service \
            --force-new-deployment \
            --region us-east-1
